name: CMake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - uses: seanmiddleditch/gha-setup-ninja@master

    - name: Set up GCC
      uses: egor-tensin/setup-gcc@v1
      with:
        version: 11

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -G Ninja -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      env:
        CXXFLAGS: -fsanitize=address
        LDFLAGS: -fsanitize=address
      run: ninja -C ${{github.workspace}}/build

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: tests/run
